version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "automerge"
    commit-message:
      prefix: "deps"
    versioning-strategy: increase
    automerges:
      - dependency-type: "development"
        match:
          update-types: ["patch"]
      - dependency-type: "production"
        match:
          update-types: ["patch"]
          security-update-only: true

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "action"
